# ===============================
# CONFIGURACION DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/vantix_pos_db
spring.datasource.username=postgres
spring.datasource.password=danilo20
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION DE HIBERNATE/JPA
# ===============================
# CAMBIO OPCION A: Cambiado temporalmente a update para que Spring cree las tablas vacias.
# Una vez que el servidor arranque y las cree, en tu PC puedes volver a ponerlo en validate.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURACION DEL SERVIDOR
# ===============================
server.port=8080
# Limite estricto de 1MB para subir archivos
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB